import = [
 "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
]

[window]
padding.x = 10
padding.y = 10
decorations = "buttonless"
opacity = 0.4
blur = true
option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 14

[scrolling]
history = 50000

[selection]
save_to_clipboard = true
